### ISSUE TITLE
Localized name for each constellations （征求AS星座翻译）

### ISSUE THREAD

**Issue by yuanjie000** [yuanjie000/AstralSorcery#2]
**当前AS的大部分汉化已经敲定的情况下，星座的汉化名仍然悬而未决，这给各方各面都带来了极大的不便，特在此开issue，尝试敲定一个合适的星座译名。各位给名称时请附上原因！**
_注：星座名称原文不拘泥于英文，有可能是自造词或拉丁语。译名在3~5个字内。etc._
[bbs的相应地址](http://www.mcbbs.net/thread-790536-1-1.html)
[作者对星座名字的解释](https://github.com/HellFirePvP/AstralSorcery/issues/628)
以下是当前星座翻译状态

星等 | 已完成星座 | 翻译（暂定） | 功能性描述 | 未完成星座（不参与星等比较 | 翻译（暂定） | 功能性描述
-- | -- | -- | -- | -- | -- | --
亮星 | Discidia | 非攻座 | Offensive | Gelu | 寒冰座 | Frigidity
亮星 | Armara | 遁甲座 | Defence | Ulteria | 避役座 | Tenacity
亮星 | Vicio | 虚御座 | Motion | Alcara | 振变座 | Resonance
亮星 | Aevitas | 生息座 | Creation | Vorux | 贪狼座 | Ferocity
亮星 | Evorsio | 解离座 | Destruction |   |   |  
暗星 | Mineralis | 晶金座 | Mineral |   |   |  
暗星 | Lucerna | 圣芒座 | Light |   |   |  
暗星 | Horologium | 时钟座* | Time |   |   |  
暗星 | Octans | 南极座* | Fishing |   |   |  
暗星 | Bootes | 牧夫座* | Herding |   |   |  
暗星 | Fornax | 天炉座* | Heat |   |   |  
暗星 | Pelotrio | 唤生座 | Convocation |   |   |  

**带*号的为真实存在的名称，不更改！**
各个星座的详细信息

> https://github.com/yuanjie000/AstralSorcery/blob/master/src/main/resources/assets/astralsorcery/lang/zh_CN.lang#L532-L604

**Comment by TartaricAcid** [comment]
补充几张游戏内的星图截图
![QQ图片20180412185448.jpg](https://i.loli.net/2018/04/12/5acf3b110d0a4.jpg)
![QQ图片20180412185452.jpg](https://i.loli.net/2018/04/12/5acf3b119ae42.jpg)
![QQ图片20180412185459.jpg](https://i.loli.net/2018/04/12/5acf3b11c49fa.jpg)
![QQ图片20180412185456.jpg](https://i.loli.net/2018/04/12/5acf3b11c49cf.jpg)

**Comment by Aaron2412** [comment]
拉丁：Horologium 时钟座
Mineralis 矿脉座
Aevitas 终身？？？
Gelu 冰川座

**Comment by touhouzun** [comment]
我认为不如根据星座的形状和功能，不太关注原名称，以“宿”命名，xi方有拉丁或造语或什么，我们也有自己的天文观_(:з)∠)_
等等这些星座的形状如此简单（？）的话那就发挥想象力吧，如“盾宿”（github没有滑稽表情和颜文字真是不方便）

**Comment by NamidaNoAnokini** [comment]
Armara=盾夫座/盾卫座/天镇座
Discidia=天戟座/双戟座
Vicio=三河座
Evorsio=悬枪座/古枪座
Aevitas=筑人座
Mineralis=天钻座
暂时只能想出这些了（ง •̀_•́）ง

**Comment by Tanimodori** [comment]
我来做维基词典的搬运工，做一下**业余**的词源考察，
不保证内容的正确性。如果有不对的地方欢迎指出。
目前有翻译（暂定）的我就偷懒不去找了

> Discidia, from Latin _discidium_, "separation, divorce; discord, disagreement"
> Armara,  from Latin _armāre_, "to arm, to reinforce"
> Vicio, from Latin _vitium_, "crime; fault, defect, blemish, error"
> Aevitas, from Latin _aevitās_ ("age"), "immortality, forever, eternity"
> Evorsio, _probably_ from Latin _ēversiō_, "expulsion, destruction, revolution"
> Mineralis, Latin _minera_ +‎ _-ālis_, "mineral"
> Lucerna, from Latin _lūceō_ ("shine, be a light"), "lamp, oil lamp"
> Horologium, Latin "clock", "时钟座"
> Pelotrio, _probably_ from Spanish _pelotreo_, "creep"
> Gelu, Latin "frost, chill"
> Unteria, Latin _unter_ + _-ia_, "far away"
> Alcara, from Portuguese _alçar_, from Latin _altus_ (“high”), "to lift; to raise"
> Vorux, _probably_ from Latin _vorax_, "voracious; gluttonous"

**Comment by MrF1995** [comment]
大概看了一下，似乎里面大部分和我们已知的星座图是不匹配的
所以我就仿照一般星座命名来随意翻了
1.干戚座
2.雏凤座
3.猎豹座
4.蛇腹座
5.槲寄生座
6.盖亚座
7.金乌座
8.时钟座（这个倒是已知的）
9.翼靴座
玩梗真愉快
希望不要有天文学大佬来打我的脸

**Comment by forestbat** [comment]
discidia双射座，armara神盾座，vicio时箭座，aevitas繁枝座，evorsio丝裂座，mineralis点金座，lucerna辉夜座，pelotrio化生座。

**Comment by 3TUSK** [comment]
我建议直接问作者这些名字都是怎么来的。
如果没有人愿意问的话我建议保留原名，就像 Thaumcraft 的要素名一样。（Thaumcraft 的要素名只有对应的释义是有翻译的，要素名本身没有翻译。）

**Comment by yuanjie000** [comment]
根据作者的解释暂时定的名称，有异议的尽快提出，没有的话我明天就提交了！

星座 | 翻译（暂定）
-- | --
Discidia | 非攻座
Armara | 钜盾座
Vicio | 虚御座
Aevitas | 生息座
Evorsio | 解离座
Mineralis | 晶金座
Lucerna | 圣芒座
Pelotrio | 唤生座
Gelu | 凝冰座\霜冰座？
Ulteria | 避役座
Alcara | 振变座
Vorux | 贪狼座

**Comment by yuanjie000** [comment]
> 钜盾座
甲御座？
