### ISSUE TITLE
Chinese translation issue for Astral Sorcery 1.9.1

### ISSUE THREAD

**Issue by mcBegins2Snow** [yuanjie000/AstralSorcery#3]
mc:1.12.2
mod:1.9.1
Astral Sorcery has been updated to 1.9.1 on June 16th,it added new items and constellations.I hope you can update zh_cn file.
By the way,I found some typos in zh_cn:
Line 162:如果祭坛祭坛周围的结构损坏->如果祭坛周围的结构损坏
Line 174:它可以想辉光粉一样抛出去->它可以像辉光粉一样抛出去
Line 225:用户->使用者
Line 237:太空->天空
Line 322:但缺无法找到来源->但却无法找到来源
Line 690:武当梯云踪->武当梯云纵 Reason:
https://baike.baidu.com/item/%E6%A2%AF%E4%BA%91%E7%BA%B5

**Comment by yuanjie000** [comment]
作者重写了手册的大部分内容，所以可能需要一段时间才能完成。

**Comment by yuanjie000** [comment]
已更新！
